apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hy9g708gp-python
  janus-idp.io/tekton: hy9g708gp-python
  backstage.io/kubernetes-id: hy9g708gp-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hy9g708gp-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
